### ISSUE TITLE
updateGuildCommands leading to an error

### ISSUE THREAD

**Issue by Libertas007** [discordeno/serverless-deno-deploy-template#15]
I have tried to make guild commands just for the purpose of tesing using `updateGuildCommands` method (of course with guild id). It gave me these 2 errors:
```
Error serving request: Error: Location:
   at Object.runMethod (https://raw.githubusercontent.com/discordeno/discordeno/main/src/rest/run_method.ts:21:11)
   at upsertSlashCommands (https://raw.githubusercontent.com/discordeno/discordeno/main/src/helpers/interactions/commands/upsert_slash_commands.ts:11:23)
   at updateGuildCommands (file:///src/src/utils/redeploy.ts:49:11)
   at Object.redeploy [as /redeploy] (file:///src/src/utils/redeploy.ts:17:16)
   at handleRequest (https://deno.land/x/sift@0.3.0/mod.ts:48:55)
   at async Event.respondWith (deno:ext/http/01_http.js:151:16)

Error: [404] The resource at the location specified doesn't exist.
   at Object.processQueue (https://raw.githubusercontent.com/discordeno/discordeno/main/src/rest/process_queue.ts:74:50)
   at async Object.processRequest (https://raw.githubusercontent.com/discordeno/discordeno/main/src/rest/process_request.ts:30:9)
```
Any ideas how to fix it?

**Comment by zabihexes** [comment]
This is just an idea, but was the bot invited with `applications.commands` scope?
**It may be caused by something different though.**

**Comment by Libertas007** [comment]
It was caused by that. **Thanks a lot!**
